'use client';

import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

type Language = 'zh' | 'en' | 'ru' | 'tg';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isLoading: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 翻译字典
const translations: Record<Language, Record<string, string>> = {
  zh: {
    // 首页
    'home.title': 'LuckyMart TJ 幸运集市',
    'home.subtitle': '1元夺宝，好运连连',
    'home.banner.title': '幸运夺宝，轻松中奖',
    'home.banner.subtitle': '超值商品，超低门槛，公平透明',
    'home.banner.button': '立即参与',
    'home.hot_products': '热门商品',
    'home.market_price': '市场价',
    'home.per_share': '每份',
    'home.total_shares': '总份数',
    'home.progress': '进度',
    'home.participate': '立即参与',
    
    // 导航
    'nav.home': '首页',
    'nav.orders': '我的订单',
    'nav.profile': '个人中心',
    'nav.resale': '转售市场',
    'nav.settings': '设置',
    'nav.transactions': '交易记录',
    'nav.withdraw': '提现',
    'nav.recharge': '充值',
    'nav.referral': '我的邀请',
    'nav.team': '团队统计',
    'nav.menu': '菜单',
    'nav.language': '语言设置',
    
    // 邀请页面
    'referral.title': '我的邀请',
    'referral.subtitle': '邀请好友，获取奖励',
    'referral.invite_code': '邀请码',
    'referral.invite_link': '邀请链接',
    'referral.copy_code': '复制邀请码',
    'referral.copy_link': '复制邀请链接',
    'referral.share_code': '分享邀请码',
    'referral.share_link': '分享邀请链接',
    'referral.invite_friends': '邀请好友',
    'referral.total_referrals': '总推荐数',
    'referral.level1_count': '一级推荐',
    'referral.level2_count': '二级推荐',
    'referral.level3_count': '三级推荐',
    'referral.total_rewards': '总奖励金额',
    'referral.weekly_rewards': '本周奖励',
    'referral.stats_title': '推荐统计',
    'referral.copy_success': '复制成功',
    'referral.copy_failed': '复制失败',
    'referral.generating_link': '生成链接中...',
    'referral.share_title': '邀请加入LuckyMart TJ',
    'referral.share_message': '注册并获得新用户奖励！使用我的邀请码或链接：',
    'referral.telegram_share': '分享到Telegram',
    'referral.whatsapp_share': '分享到WhatsApp',
    'referral.social_share': '社交分享',
    
    // 推荐列表页面
    'referral.list.title': '推荐列表',
    'referral.list.subtitle': '查看您推荐的用户详细信息',
    'referral.list.username': '用户名',
    'referral.list.referral_level': '推荐级别',
    'referral.list.level': '级别',
    'referral.list.join_date': '加入时间',
    'referral.list.total_consumption': '总消费',
    'referral.list.rewards': '贡献奖励',
    'referral.list.status': '状态',
    'referral.list.active': '活跃',
    'referral.list.inactive': '非活跃',
    'referral.list.last_active': '最后活跃',
    'referral.list.records': '条记录',
    'referral.list.filters': '筛选',
    'referral.list.search_placeholder': '搜索用户名...',
    'referral.list.all_levels': '所有级别',
    'referral.list.all_status': '所有状态',
    'referral.list.clear_filters': '清除筛选',
    'referral.list.page_info': '显示 {start} - {end} 条，共 {total} 条',
    'referral.list.page': '页',
    'referral.list.loading': '加载中...',
    'referral.list.no_data': '暂无数据',
    'referral.list.error_title': '加载失败',
    'referral.list.retry': '重试',
    'referral.list.export_success': '导出成功',
    'referral.list.export_failed': '导出失败',
    'referral.list.sheet_name': '推荐列表',
    
    // 团队统计页面
    'team.title': '团队统计',
    'team.subtitle': '团队数据分析与管理',
    'team.overview': '概况',
    'team.growth': '增长',
    'team.ranking': '排行',
    'team.overview_title': '团队概况',
    'team.overview_subtitle': '团队核心数据统计',
    'team.growth_title': '团队增长',
    'team.growth_subtitle': '团队发展趋势分析',
    'team.total_members': '总成员数',
    'team.active_members': '活跃成员',
    'team.active_rate': '活跃率',
    'team.total_revenue': '总收益',
    'team.level_distribution': '级别分布',
    'team.level_distribution_desc': '团队成员级别分布情况',
    'team.level1': '一级',
    'team.level2': '二级',
    'team.level3': '三级',
    'team.level4': '四级',
    'team.level5': '五级',
    'team.activity_stats': '活跃度统计',
    'team.activity_stats_desc': '团队成员活跃情况分析',
    'team.avg_active_days': '平均活跃天数',
    'team.most_active_days': '最多活跃天数',
    'team.least_active_days': '最少活跃天数',
    'team.overall_activity': '整体活跃度',
    'team.new_members_trend': '新成员趋势',
    'team.new_members_trend_desc': '近期新成员增长情况',
    'team.performance_overview': '业绩概览',
    'team.performance_overview_desc': '团队核心业绩指标',
    'team.top_performer': '最佳业绩',
    'team.avg_revenue': '平均收益',
    'team.revenue_per_member': '人均收益',
    'team.growth_rate': '增长率',
    'team.member_growth_rate': '成员增长率',
    'team.revenue_growth_rate': '收益增长率',
    'team.member_growth_trend': '成员增长趋势',
    'team.member_growth_trend_desc': '团队成员数量变化趋势',
    'team.new_members': '新成员',
    'team.revenue_growth_trend': '收益增长趋势',
    'team.revenue_growth_trend_desc': '团队收益变化趋势',
    'team.revenue': '收益',
    'team.comprehensive_growth_analysis': '综合增长分析',
    'team.comprehensive_growth_analysis_desc': '多维度团队增长数据分析',
    'team.growth_insights': '增长洞察',
    'team.member_growth_insight': '成员增长洞察',
    'team.revenue_growth_insight': '收益增长洞察',
    'team.overall_performance': '整体表现',
    'team.positive_trend': '积极趋势',
    'team.negative_trend': '消极趋势',
    'team.performance_ranking': '业绩排行榜',
    'team.referral_ranking': '推荐排行榜',
    'team.referrals': '推荐数',
    'team.active_days': '活跃天数',
    'team.total_referrals': '总推荐数',
    'team.members': '成员',
    
    // 图表页面
    'referral.charts.title': '推荐数据可视化',
    'referral.charts.subtitle': '通过图表分析推荐数据趋势',
    'referral.charts.referral_count': '推荐数统计',
    'referral.charts.level_distribution': '级别分布',
    'referral.charts.reward_trend': '奖励趋势',
    'referral.charts.total_referrals': '总推荐数',
    'referral.charts.total_rewards': '总奖励金额',
    'referral.charts.active_users': '活跃用户',
    'referral.charts.active_rate': '活跃率',
    'referral.charts.level_1': '一级推荐',
    'referral.charts.level_2': '二级推荐',
    'referral.charts.level_3': '三级推荐',
    'referral.charts.level_1_rewards': '一级奖励',
    'referral.charts.level_2_rewards': '二级奖励',
    'referral.charts.level_3_rewards': '三级奖励',
    'referral.charts.cumulative_rewards': '累计奖励',
    'referral.charts.7_days': '7天',
    'referral.charts.30_days': '30天',
    'referral.charts.90_days': '90天',
    'referral.charts.1_year': '1年',
    'referral.charts.export': '导出图表',
    'referral.charts.chart_info': '图表说明',
    'referral.charts.referral_stats_info': '显示各时间段的推荐数统计，包括一级、二级和三级推荐的数量分布',
    'referral.charts.level_distribution_info': '显示推荐用户的级别分布比例，帮助了解推荐结构',
    'referral.charts.reward_trend_info': '显示各时间段获得的奖励金额趋势，包括各级别奖励和累计奖励',
    'referral.charts.loading': '加载图表数据...',
    'referral.charts.error_title': '图表加载失败',
    'referral.charts.retry': '重试',
    'referral.charts.export_failed': '图表导出失败',
    
    // 商品详情
    'product.detail': '商品详情',
    'product.description': '商品描述',
    'product.market_price': '市场价',
    'product.total_shares': '总份数',
    'product.price_per_share': '每份价格',
    'product.participation_progress': '参与进度',
    'product.remaining': '剩余',
    'product.select_shares': '选择份数',
    'product.need_coins': '需要',
    'product.participate_now': '立即参与',
    'product.participating': '参与中...',
    'product.recent_participations': '最近参与',
    'product.agree_rules': '参与即表示同意平台规则，祝您好运！',
    
    // 通用
    'common.loading': '加载中...',
    'common.shares': '份',
    'common.coins': '夺宝币',
    'common.tjs': 'TJS',
    'common.back': '返回',
    'common.confirm': '确认',
    'common.cancel': '取消',
    
    // 管理后台
    'admin.welcome': '欢迎',
    'admin.logout': '退出登录',
    
    // 奖励配置管理
    'admin.reward_config.title': '奖励配置管理',
    'admin.reward_config.subtitle': '管理系统奖励参数和推荐级别',
    'admin.reward_config.search_placeholder': '搜索配置键名或名称...',
    'admin.reward_config.add_new': '新增配置',
    'admin.reward_config.total_configs': '总配置数',
    'admin.reward_config.active_configs': '启用配置',
    'admin.reward_config.inactive_configs': '禁用配置',
    'admin.reward_config.current_page': '当前页',
    'admin.reward_config.no_configs': '暂无配置',
    'admin.reward_config.no_configs_description': '点击新增按钮创建第一个奖励配置',
    'admin.reward_config.config_key': '配置键名',
    'admin.reward_config.config_name': '配置名称',
    'admin.reward_config.reward_amount': '奖励金额',
    'admin.reward_config.referral_level': '推荐级别',
    'admin.reward_config.status': '状态',
    'admin.reward_config.updated_at': '更新时间',
    'admin.reward_config.updated_by': '修改人',
    'admin.reward_config.actions': '操作',
    'admin.reward_config.active': '启用',
    'admin.reward_config.inactive': '禁用',
    'admin.reward_config.level': '级别',
    'admin.reward_config.no_level': '无级别',
    'admin.reward_config.all_levels': '所有级别',
    'admin.reward_config.all_status': '所有状态',
    'admin.reward_config.edit': '编辑',
    'admin.reward_config.deactivate': '禁用',
    'admin.reward_config.activate': '启用',
    'admin.reward_config.previous': '上一页',
    'admin.reward_config.next': '下一页',
    'admin.reward_config.page_info': '第{page}页，共{totalPages}页',
    'admin.reward_config.add_config': '新增配置',
    'admin.reward_config.edit_config': '编辑配置',
    'admin.reward_config.select_template': '选择预设模板',
    'admin.reward_config.config_key_placeholder': '例如：register_referrer',
    'admin.reward_config.config_name_placeholder': '例如：推荐人注册奖励',
    'admin.reward_config.config_description_placeholder': '可选的配置描述...',
    'admin.reward_config.referral_level_description': '设置奖励对应的推荐级别',
    'admin.reward_config.enable_config': '启用此配置',
    'admin.reward_config.update': '更新',
    'admin.reward_config.create': '创建',
    'admin.reward_config.updating': '更新中...',
    'admin.reward_config.creating': '创建中...',
    // 批量操作相关翻译
    'admin.reward_config.select_all': '全选',
    'admin.reward_config.clear_selection': '取消选择',
    'admin.reward_config.batch_update': '批量修改',
    'admin.reward_config.selected_count': '已选择 {count} 项',
    'admin.reward_config.select': '选择',
    'admin.reward_config.deselect': '取消选择',
  },
  en: {
    // Home
    'home.title': 'LuckyMart TJ',
    'home.subtitle': 'Win Big for Just $1',
    'home.banner.title': 'Lucky Draw, Easy Win',
    'home.banner.subtitle': 'Premium Products, Low Entry, Fair & Transparent',
    'home.banner.button': 'Join Now',
    'home.hot_products': 'Hot Products',
    'home.market_price': 'Market Price',
    'home.per_share': 'Per Share',
    'home.total_shares': 'Total Shares',
    'home.progress': 'Progress',
    'home.participate': 'Join Now',
    
    // Navigation
    'nav.home': 'Home',
    'nav.orders': 'My Orders',
    'nav.profile': 'Profile',
    'nav.resale': 'Resale Market',
    'nav.settings': 'Settings',
    'nav.transactions': 'Transactions',
    'nav.withdraw': 'Withdraw',
    'nav.recharge': 'Recharge',
    'nav.referral': 'My Referrals',
    'nav.team': 'Team Stats',
    'nav.menu': 'Menu',
    'nav.language': 'Language',
    
    // Referral Page
    'referral.title': 'My Referrals',
    'referral.subtitle': 'Invite friends, earn rewards',
    'referral.invite_code': 'Invite Code',
    'referral.invite_link': 'Invite Link',
    'referral.copy_code': 'Copy Code',
    'referral.copy_link': 'Copy Link',
    'referral.share_code': 'Share Code',
    'referral.share_link': 'Share Link',
    'referral.invite_friends': 'Invite Friends',
    'referral.total_referrals': 'Total Referrals',
    'referral.level1_count': 'Level 1',
    'referral.level2_count': 'Level 2',
    'referral.level3_count': 'Level 3',
    'referral.total_rewards': 'Total Rewards',
    'referral.weekly_rewards': 'Weekly Rewards',
    'referral.stats_title': 'Referral Statistics',
    'referral.copy_success': 'Copied Successfully',
    'referral.copy_failed': 'Copy Failed',
    'referral.generating_link': 'Generating Link...',
    'referral.share_title': 'Join LuckyMart TJ',
    'referral.share_message': 'Register and get new user rewards! Use my invite code or link:',
    'referral.telegram_share': 'Share to Telegram',
    'referral.whatsapp_share': 'Share to WhatsApp',
    'referral.social_share': 'Social Share',
    
    // Referral List Page
    'referral.list.title': 'Referral List',
    'referral.list.subtitle': 'View detailed information of your referred users',
    'referral.list.username': 'Username',
    'referral.list.referral_level': 'Referral Level',
    'referral.list.level': 'Level',
    'referral.list.join_date': 'Join Date',
    'referral.list.total_consumption': 'Total Consumption',
    'referral.list.rewards': 'Contribution Rewards',
    'referral.list.status': 'Status',
    'referral.list.active': 'Active',
    'referral.list.inactive': 'Inactive',
    'referral.list.last_active': 'Last Active',
    'referral.list.records': 'records',
    'referral.list.filters': 'Filters',
    'referral.list.search_placeholder': 'Search username...',
    'referral.list.all_levels': 'All Levels',
    'referral.list.all_status': 'All Status',
    'referral.list.clear_filters': 'Clear Filters',
    'referral.list.page_info': 'Showing {start} - {end} of {total}',
    'referral.list.page': 'page',
    'referral.list.loading': 'Loading...',
    'referral.list.no_data': 'No data available',
    'referral.list.error_title': 'Loading Failed',
    'referral.list.retry': 'Retry',
    'referral.list.export_success': 'Export successful',
    'referral.list.export_failed': 'Export failed',
    'referral.list.sheet_name': 'Referral List',
    
    // Team Statistics Page
    'team.title': 'Team Statistics',
    'team.subtitle': 'Team data analysis and management',
    'team.overview': 'Overview',
    'team.growth': 'Growth',
    'team.ranking': 'Ranking',
    'team.overview_title': 'Team Overview',
    'team.overview_subtitle': 'Core team data statistics',
    'team.growth_title': 'Team Growth',
    'team.growth_subtitle': 'Team development trend analysis',
    'team.total_members': 'Total Members',
    'team.active_members': 'Active Members',
    'team.active_rate': 'Active Rate',
    'team.total_revenue': 'Total Revenue',
    'team.level_distribution': 'Level Distribution',
    'team.level_distribution_desc': 'Team member level distribution',
    'team.level1': 'Level 1',
    'team.level2': 'Level 2',
    'team.level3': 'Level 3',
    'team.level4': 'Level 4',
    'team.level5': 'Level 5',
    'team.activity_stats': 'Activity Statistics',
    'team.activity_stats_desc': 'Team member activity analysis',
    'team.avg_active_days': 'Average Active Days',
    'team.most_active_days': 'Most Active Days',
    'team.least_active_days': 'Least Active Days',
    'team.overall_activity': 'Overall Activity',
    'team.new_members_trend': 'New Members Trend',
    'team.new_members_trend_desc': 'Recent new member growth',
    'team.performance_overview': 'Performance Overview',
    'team.performance_overview_desc': 'Core team performance metrics',
    'team.top_performer': 'Top Performer',
    'team.avg_revenue': 'Average Revenue',
    'team.revenue_per_member': 'Revenue per Member',
    'team.growth_rate': 'Growth Rate',
    'team.member_growth_rate': 'Member Growth Rate',
    'team.revenue_growth_rate': 'Revenue Growth Rate',
    'team.member_growth_trend': 'Member Growth Trend',
    'team.member_growth_trend_desc': 'Team member count change trend',
    'team.new_members': 'New Members',
    'team.revenue_growth_trend': 'Revenue Growth Trend',
    'team.revenue_growth_trend_desc': 'Team revenue change trend',
    'team.revenue': 'Revenue',
    'team.comprehensive_growth_analysis': 'Comprehensive Growth Analysis',
    'team.comprehensive_growth_analysis_desc': 'Multi-dimensional team growth data analysis',
    'team.growth_insights': 'Growth Insights',
    'team.member_growth_insight': 'Member Growth Insight',
    'team.revenue_growth_insight': 'Revenue Growth Insight',
    'team.overall_performance': 'Overall Performance',
    'team.positive_trend': 'Positive Trend',
    'team.negative_trend': 'Negative Trend',
    'team.performance_ranking': 'Performance Ranking',
    'team.referral_ranking': 'Referral Ranking',
    'team.referrals': 'Referrals',
    'team.active_days': 'Active Days',
    'team.total_referrals': 'Total Referrals',
    'team.members': 'Members',
    
    // Charts Page
    'referral.charts.title': 'Referral Data Visualization',
    'referral.charts.subtitle': 'Analyze referral data trends through charts',
    'referral.charts.referral_count': 'Referral Count',
    'referral.charts.level_distribution': 'Level Distribution',
    'referral.charts.reward_trend': 'Reward Trend',
    'referral.charts.total_referrals': 'Total Referrals',
    'referral.charts.total_rewards': 'Total Rewards',
    'referral.charts.active_users': 'Active Users',
    'referral.charts.active_rate': 'Active Rate',
    'referral.charts.level_1': 'Level 1',
    'referral.charts.level_2': 'Level 2',
    'referral.charts.level_3': 'Level 3',
    'referral.charts.level_1_rewards': 'Level 1 Rewards',
    'referral.charts.level_2_rewards': 'Level 2 Rewards',
    'referral.charts.level_3_rewards': 'Level 3 Rewards',
    'referral.charts.cumulative_rewards': 'Cumulative Rewards',
    'referral.charts.7_days': '7 Days',
    'referral.charts.30_days': '30 Days',
    'referral.charts.90_days': '90 Days',
    'referral.charts.1_year': '1 Year',
    'referral.charts.export': 'Export Chart',
    'referral.charts.chart_info': 'Chart Information',
    'referral.charts.referral_stats_info': 'Shows referral count statistics for each time period, including distribution of Level 1, 2, and 3 referrals',
    'referral.charts.level_distribution_info': 'Shows the proportion of referral users by level, helping understand the referral structure',
    'referral.charts.reward_trend_info': 'Shows reward amount trends for each time period, including rewards by level and cumulative rewards',
    'referral.charts.loading': 'Loading chart data...',
    'referral.charts.error_title': 'Chart Loading Failed',
    'referral.charts.retry': 'Retry',
    'referral.charts.export_failed': 'Chart export failed',
    
    // Product Detail
    'product.detail': 'Product Detail',
    'product.description': 'Description',
    'product.market_price': 'Market Price',
    'product.total_shares': 'Total Shares',
    'product.price_per_share': 'Price per Share',
    'product.participation_progress': 'Participation Progress',
    'product.remaining': 'Remaining',
    'product.select_shares': 'Select Shares',
    'product.need_coins': 'Need',
    'product.participate_now': 'Join Now',
    'product.participating': 'Joining...',
    'product.recent_participations': 'Recent Participants',
    'product.agree_rules': 'By participating, you agree to the platform rules. Good luck!',
    
    // Common
    'common.loading': 'Loading...',
    'common.shares': 'shares',
    'common.coins': 'coins',
    'common.tjs': 'TJS',
    'common.back': 'Back',
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    
    // Admin
    'admin.welcome': 'Welcome',
    'admin.logout': 'Logout',
    
    // Reward Config Management
    'admin.reward_config.title': 'Reward Config Management',
    'admin.reward_config.subtitle': 'Manage system reward parameters and referral levels',
    'admin.reward_config.search_placeholder': 'Search config key or name...',
    'admin.reward_config.add_new': 'Add New',
    'admin.reward_config.total_configs': 'Total Configs',
    'admin.reward_config.active_configs': 'Active Configs',
    'admin.reward_config.inactive_configs': 'Inactive Configs',
    'admin.reward_config.current_page': 'Current Page',
    'admin.reward_config.no_configs': 'No configs',
    'admin.reward_config.no_configs_description': 'Click add button to create your first reward config',
    'admin.reward_config.config_key': 'Config Key',
    'admin.reward_config.config_name': 'Config Name',
    'admin.reward_config.reward_amount': 'Reward Amount',
    'admin.reward_config.referral_level': 'Referral Level',
    'admin.reward_config.status': 'Status',
    'admin.reward_config.updated_at': 'Updated At',
    'admin.reward_config.updated_by': 'Updated By',
    'admin.reward_config.actions': 'Actions',
    'admin.reward_config.active': 'Active',
    'admin.reward_config.inactive': 'Inactive',
    'admin.reward_config.level': 'Level',
    'admin.reward_config.no_level': 'No Level',
    'admin.reward_config.all_levels': 'All Levels',
    'admin.reward_config.all_status': 'All Status',
    'admin.reward_config.edit': 'Edit',
    'admin.reward_config.deactivate': 'Deactivate',
    'admin.reward_config.activate': 'Activate',
    'admin.reward_config.previous': 'Previous',
    'admin.reward_config.next': 'Next',
    'admin.reward_config.page_info': 'Page {page} of {totalPages}',
    'admin.reward_config.add_config': 'Add Config',
    'admin.reward_config.edit_config': 'Edit Config',
    'admin.reward_config.select_template': 'Select Template',
    'admin.reward_config.config_key_placeholder': 'e.g. register_referrer',
    'admin.reward_config.config_name_placeholder': 'e.g. Referrer Registration Reward',
    'admin.reward_config.config_description_placeholder': 'Optional config description...',
    'admin.reward_config.referral_level_description': 'Set the referral level for this reward',
    'admin.reward_config.enable_config': 'Enable this config',
    'admin.reward_config.update': 'Update',
    'admin.reward_config.create': 'Create',
    'admin.reward_config.updating': 'Updating...',
    'admin.reward_config.creating': 'Creating...',
    // Batch operations
    'admin.reward_config.select_all': 'Select All',
    'admin.reward_config.clear_selection': 'Clear Selection',
    'admin.reward_config.batch_update': 'Batch Update',
    'admin.reward_config.selected_count': '{count} selected',
    'admin.reward_config.select': 'Select',
    'admin.reward_config.deselect': 'Deselect',
    'admin.reward_config.confirm': 'Confirm',
    'admin.reward_config.confirm_execute': 'Confirm Execute',
    'admin.reward_config.close': 'Close',
    
    // 配置修改历史管理
    'admin.config_history.title': 'Config History Management',
    'admin.config_history.subtitle': 'View configuration modification history and audit records',
    'admin.config_history.search': 'Search',
    'admin.config_history.reset': 'Reset',
    'admin.config_history.startDate': 'Start Date',
    'admin.config_history.endDate': 'End Date',
    'admin.config_history.updatedBy': 'Modified By',
    'admin.config_history.configKey': 'Config Key',
    'admin.config_history.time': 'Time',
    'admin.config_history.modifier': 'Modifier',
    'admin.config_history.beforeValue': 'Before Value',
    'admin.config_history.afterValue': 'After Value',
    'admin.config_history.ipAddress': 'IP Address',
    'admin.config_history.changeType': 'Change Type',
    'admin.config_history.create': 'Create',
    'admin.config_history.delete': 'Delete',
    'admin.config_history.increase': 'Increase',
    'admin.config_history.decrease': 'Decrease',
    'admin.config_history.modify': 'Modify',
    'admin.config_history.none': 'None',
    'admin.config_history.page': 'Page',
    'admin.config_history.of': 'of',
    'admin.config_history.total': 'Total',
    'admin.config_history.noRecords': 'No records found',
    'admin.config_history.loading': 'Loading...',
    'admin.config_history.placeholder.key': 'Enter config key...',
    'admin.config_history.placeholder.modifier': 'Enter modifier...',
  },
  ru: {
    // Главная
    'home.title': 'LuckyMart TJ Лотерея',
    'home.subtitle': 'Выиграй по 1 сомони',
    'home.banner.title': 'Лотерея удачи, легкий выигрыш',
    'home.banner.subtitle': 'Ценные товары, низкий порог, честно и прозрачно',
    'home.banner.button': 'Участвовать',
    'home.hot_products': 'Популярные товары',
    'home.market_price': 'Рыночная цена',
    'home.per_share': 'За долю',
    'home.total_shares': 'Всего долей',
    'home.progress': 'Прогресс',
    'home.participate': 'Участвовать',
    
    // Навигация
    'nav.home': 'Главная',
    'nav.orders': 'Мои заказы',
    'nav.profile': 'Профиль',
    'nav.resale': 'Вторичный рынок',
    'nav.settings': 'Настройки',
    'nav.transactions': 'Транзакции',
    'nav.withdraw': 'Вывод средств',
    'nav.recharge': 'Пополнение',
    'nav.referral': 'Мои приглашения',
    'nav.team': 'Статистика команды',
    'nav.menu': 'Меню',
    'nav.language': 'Язык',
    
    // Страница приглашений
    'referral.title': 'Мои приглашения',
    'referral.subtitle': 'Приглашайте друзей, получайте награды',
    'referral.invite_code': 'Код приглашения',
    'referral.invite_link': 'Ссылка приглашения',
    'referral.copy_code': 'Копировать код',
    'referral.copy_link': 'Копировать ссылку',
    'referral.share_code': 'Поделиться кодом',
    'referral.share_link': 'Поделиться ссылкой',
    'referral.invite_friends': 'Пригласить друзей',
    'referral.total_referrals': 'Всего приглашений',
    'referral.level1_count': 'Уровень 1',
    'referral.level2_count': 'Уровень 2',
    'referral.level3_count': 'Уровень 3',
    'referral.total_rewards': 'Общая награда',
    'referral.weekly_rewards': 'Награды за неделю',
    'referral.stats_title': 'Статистика приглашений',
    'referral.copy_success': 'Скопировано успешно',
    'referral.copy_failed': 'Не удалось скопировать',
    'referral.generating_link': 'Генерация ссылки...',
    'referral.share_title': 'Присоединяйтесь к LuckyMart TJ',
    'referral.share_message': 'Зарегистрируйтесь и получите награду нового пользователя! Используйте мой код приглашения или ссылку:',
    'referral.telegram_share': 'Поделиться в Telegram',
    'referral.whatsapp_share': 'Поделиться в WhatsApp',
    'referral.social_share': 'Социальные сети',
    
    // Страница списка приглашений
    'referral.list.title': 'Список приглашений',
    'referral.list.subtitle': 'Просмотр подробной информации о приглашенных пользователях',
    'referral.list.username': 'Имя пользователя',
    'referral.list.referral_level': 'Уровень приглашения',
    'referral.list.level': 'Уровень',
    'referral.list.join_date': 'Дата присоединения',
    'referral.list.total_consumption': 'Общее потребление',
    'referral.list.rewards': 'Награды за вклад',
    'referral.list.status': 'Статус',
    'referral.list.active': 'Активный',
    'referral.list.inactive': 'Неактивный',
    'referral.list.last_active': 'Последняя активность',
    'referral.list.records': 'записей',
    'referral.list.filters': 'Фильтры',
    'referral.list.search_placeholder': 'Поиск имени пользователя...',
    'referral.list.all_levels': 'Все уровни',
    'referral.list.all_status': 'Все статусы',
    'referral.list.clear_filters': 'Очистить фильтры',
    'referral.list.page_info': 'Показано {start} - {end} из {total}',
    'referral.list.page': 'страница',
    'referral.list.loading': 'Загрузка...',
    'referral.list.no_data': 'Нет данных',
    'referral.list.error_title': 'Ошибка загрузки',
    'referral.list.retry': 'Повторить',
    'referral.list.export_success': 'Экспорт успешен',
    'referral.list.export_failed': 'Ошибка экспорта',
    'referral.list.sheet_name': 'Список приглашений',
    
    // Страница статистики команды
    'team.title': 'Статистика команды',
    'team.subtitle': 'Анализ и управление данными команды',
    'team.overview': 'Обзор',
    'team.growth': 'Рост',
    'team.ranking': 'Рейтинг',
    'team.overview_title': 'Обзор команды',
    'team.overview_subtitle': 'Основная статистика команды',
    'team.growth_title': 'Рост команды',
    'team.growth_subtitle': 'Анализ тенденций развития команды',
    'team.total_members': 'Всего участников',
    'team.active_members': 'Активные участники',
    'team.active_rate': 'Уровень активности',
    'team.total_revenue': 'Общий доход',
    'team.level_distribution': 'Распределение по уровням',
    'team.level_distribution_desc': 'Распределение участников команды по уровням',
    'team.level1': 'Уровень 1',
    'team.level2': 'Уровень 2',
    'team.level3': 'Уровень 3',
    'team.level4': 'Уровень 4',
    'team.level5': 'Уровень 5',
    'team.activity_stats': 'Статистика активности',
    'team.activity_stats_desc': 'Анализ активности участников команды',
    'team.avg_active_days': 'Средние активные дни',
    'team.most_active_days': 'Максимум активных дней',
    'team.least_active_days': 'Минимум активных дней',
    'team.overall_activity': 'Общая активность',
    'team.new_members_trend': 'Тренд новых участников',
    'team.new_members_trend_desc': 'Недавний рост новых участников',
    'team.performance_overview': 'Обзор эффективности',
    'team.performance_overview_desc': 'Ключевые показатели эффективности команды',
    'team.top_performer': 'Лучший результат',
    'team.avg_revenue': 'Средний доход',
    'team.revenue_per_member': 'Доход на участника',
    'team.growth_rate': 'Темп роста',
    'team.member_growth_rate': 'Темп роста участников',
    'team.revenue_growth_rate': 'Темп роста дохода',
    'team.member_growth_trend': 'Тренд роста участников',
    'team.member_growth_trend_desc': 'Тренд изменения количества участников команды',
    'team.new_members': 'Новые участники',
    'team.revenue_growth_trend': 'Тренд роста дохода',
    'team.revenue_growth_trend_desc': 'Тренд изменения дохода команды',
    'team.revenue': 'Доход',
    'team.comprehensive_growth_analysis': 'Комплексный анализ роста',
    'team.comprehensive_growth_analysis_desc': 'Многомерный анализ данных роста команды',
    'team.growth_insights': 'Инсайты роста',
    'team.member_growth_insight': 'Инсайт роста участников',
    'team.revenue_growth_insight': 'Инсайт роста дохода',
    'team.overall_performance': 'Общая производительность',
    'team.positive_trend': 'Положительная тенденция',
    'team.negative_trend': 'Отрицательная тенденция',
    'team.performance_ranking': 'Рейтинг эффективности',
    'team.referral_ranking': 'Рейтинг приглашений',
    'team.referrals': 'Приглашения',
    'team.active_days': 'Активные дни',
    'team.total_referrals': 'Всего приглашений',
    'team.members': 'Участники',
    
    // Страница графиков
    'referral.charts.title': 'Визуализация данных приглашений',
    'referral.charts.subtitle': 'Анализ тенденций данных приглашений через графики',
    'referral.charts.referral_count': 'Количество приглашений',
    'referral.charts.level_distribution': 'Распределение по уровням',
    'referral.charts.reward_trend': 'Тренд наград',
    'referral.charts.total_referrals': 'Всего приглашений',
    'referral.charts.total_rewards': 'Общая сумма наград',
    'referral.charts.active_users': 'Активные пользователи',
    'referral.charts.active_rate': 'Уровень активности',
    'referral.charts.level_1': 'Уровень 1',
    'referral.charts.level_2': 'Уровень 2',
    'referral.charts.level_3': 'Уровень 3',
    'referral.charts.level_1_rewards': 'Награды уровня 1',
    'referral.charts.level_2_rewards': 'Награды уровня 2',
    'referral.charts.level_3_rewards': 'Награды уровня 3',
    'referral.charts.cumulative_rewards': 'Накопительные награды',
    'referral.charts.7_days': '7 дней',
    'referral.charts.30_days': '30 дней',
    'referral.charts.90_days': '90 дней',
    'referral.charts.1_year': '1 год',
    'referral.charts.export': 'Экспорт графика',
    'referral.charts.chart_info': 'Информация о графике',
    'referral.charts.referral_stats_info': 'Показывает статистику количества приглашений за каждый период времени, включая распределение приглашений уровней 1, 2 и 3',
    'referral.charts.level_distribution_info': 'Показывает пропорцию приглашенных пользователей по уровням, помогая понять структуру приглашений',
    'referral.charts.reward_trend_info': 'Показывает тенденции сумм наград за каждый период времени, включая награды по уровням и накопительные награды',
    'referral.charts.loading': 'Загрузка данных графика...',
    'referral.charts.error_title': 'Ошибка загрузки графика',
    'referral.charts.retry': 'Повторить',
    'referral.charts.export_failed': 'Ошибка экспорта графика',
    
    // Детали товара
    'product.detail': 'Детали товара',
    'product.description': 'Описание',
    'product.market_price': 'Рыночная цена',
    'product.total_shares': 'Всего долей',
    'product.price_per_share': 'Цена за долю',
    'product.participation_progress': 'Прогресс участия',
    'product.remaining': 'Осталось',
    'product.select_shares': 'Выберите доли',
    'product.need_coins': 'Требуется',
    'product.participate_now': 'Участвовать сейчас',
    'product.participating': 'Участие...',
    'product.recent_participations': 'Недавние участники',
    'product.agree_rules': 'Участвуя, вы соглашаетесь с правилами платформы. Удачи!',
    
    // Общее
    'common.loading': 'Загрузка...',
    'common.shares': 'долей',
    'common.coins': 'монет',
    'common.tjs': 'TJS',
    'common.back': 'Назад',
    'common.confirm': 'Подтвердить',
    'common.cancel': 'Отмена',
    
    // Админ
    'admin.welcome': 'Добро пожаловать',
    'admin.logout': 'Выйти',
    
    // Управление наградами
    'admin.reward_config.title': 'Управление наградами',
    'admin.reward_config.subtitle': 'Управление параметрами наград и уровнями рефералов',
    'admin.reward_config.search_placeholder': 'Поиск по ключу или имени...',
    'admin.reward_config.add_new': 'Добавить новый',
    'admin.reward_config.total_configs': 'Всего конфигураций',
    'admin.reward_config.active_configs': 'Активные конфигурации',
    'admin.reward_config.inactive_configs': 'Неактивные конфигурации',
    'admin.reward_config.current_page': 'Текущая страница',
    'admin.reward_config.no_configs': 'Нет конфигураций',
    'admin.reward_config.no_configs_description': 'Нажмите добавить для создания первой конфигурации наград',
    'admin.reward_config.config_key': 'Ключ конфигурации',
    'admin.reward_config.config_name': 'Имя конфигурации',
    'admin.reward_config.reward_amount': 'Сумма награды',
    'admin.reward_config.referral_level': 'Уровень реферала',
    'admin.reward_config.status': 'Статус',
    'admin.reward_config.updated_at': 'Обновлено',
    'admin.reward_config.updated_by': 'Обновил',
    'admin.reward_config.actions': 'Действия',
    'admin.reward_config.active': 'Активный',
    'admin.reward_config.inactive': 'Неактивный',
    'admin.reward_config.level': 'Уровень',
    'admin.reward_config.no_level': 'Без уровня',
    'admin.reward_config.all_levels': 'Все уровни',
    'admin.reward_config.all_status': 'Все статусы',
    'admin.reward_config.edit': 'Редактировать',
    'admin.reward_config.deactivate': 'Деактивировать',
    'admin.reward_config.activate': 'Активировать',
    'admin.reward_config.previous': 'Назад',
    'admin.reward_config.next': 'Вперед',
    'admin.reward_config.page_info': 'Страница {page} из {totalPages}',
    'admin.reward_config.add_config': 'Добавить конфигурацию',
    'admin.reward_config.edit_config': 'Редактировать конфигурацию',
    'admin.reward_config.select_template': 'Выбрать шаблон',
    'admin.reward_config.config_key_placeholder': 'например register_referrer',
    'admin.reward_config.config_name_placeholder': 'например Награда за регистрацию реферера',
    'admin.reward_config.config_description_placeholder': 'Описание конфигурации (необязательно)...',
    'admin.reward_config.referral_level_description': 'Установить уровень реферала для этой награды',
    'admin.reward_config.enable_config': 'Включить эту конфигурацию',
    'admin.reward_config.update': 'Обновить',
    'admin.reward_config.create': 'Создать',
    'admin.reward_config.updating': 'Обновление...',
    'admin.reward_config.creating': 'Создание...',
    // Пакетные операции
    'admin.reward_config.select_all': 'Выбрать все',
    'admin.reward_config.clear_selection': 'Снять выбор',
    'admin.reward_config.batch_update': 'Пакетное обновление',
    'admin.reward_config.selected_count': 'Выбрано {count}',
    'admin.reward_config.select': 'Выбрать',
    'admin.reward_config.deselect': 'Снять выбор',
    'admin.reward_config.confirm': 'Подтвердить',
    'admin.reward_config.confirm_execute': 'Подтвердить выполнение',
    'admin.reward_config.close': 'Закрыть',
    
    // Управление историей изменений конфигурации
    'admin.config_history.title': 'Управление историей конфигурации',
    'admin.config_history.subtitle': 'Просмотр истории изменений конфигурации и записей аудита',
    'admin.config_history.search': 'Поиск',
    'admin.config_history.reset': 'Сбросить',
    'admin.config_history.startDate': 'Дата начала',
    'admin.config_history.endDate': 'Дата окончания',
    'admin.config_history.updatedBy': 'Изменил',
    'admin.config_history.configKey': 'Ключ конфигурации',
    'admin.config_history.time': 'Время',
    'admin.config_history.modifier': 'Изменивший',
    'admin.config_history.beforeValue': 'Предыдущее значение',
    'admin.config_history.afterValue': 'Новое значение',
    'admin.config_history.ipAddress': 'IP адрес',
    'admin.config_history.changeType': 'Тип изменения',
    'admin.config_history.create': 'Создание',
    'admin.config_history.delete': 'Удаление',
    'admin.config_history.increase': 'Увеличение',
    'admin.config_history.decrease': 'Уменьшение',
    'admin.config_history.modify': 'Изменение',
    'admin.config_history.none': 'Нет',
    'admin.config_history.page': 'Страница',
    'admin.config_history.of': 'из',
    'admin.config_history.total': 'Всего',
    'admin.config_history.noRecords': 'Записи не найдены',
    'admin.config_history.loading': 'Загрузка...',
    'admin.config_history.placeholder.key': 'Введите ключ конфигурации...',
    'admin.config_history.placeholder.modifier': 'Введите изменившего...',
  },
  tg: {
    // Асосӣ
    'home.title': 'LuckyMart TJ Лутфи',
    'home.subtitle': 'Бо 1 сомонӣ ҷойгир шавед',
    'home.banner.title': 'Лутфи қисмат, ғолибшавӣ осон',
    'home.banner.subtitle': 'Маҳсулоти арзан, талаботи паст, адолатнок ва шаффоф',
    'home.banner.button': 'Иштирок кунед',
    'home.hot_products': 'Маҳсулоти машҳур',
    'home.market_price': 'Нархи бозор',
    'home.per_share': 'Барои ҳисса',
    'home.total_shares': 'Ҳиссаҳои умумӣ',
    'home.progress': 'Пешрафт',
    'home.participate': 'Иштирок кунед',
    
    // Навигатсия
    'nav.home': 'Саҳифаи асосӣ',
    'nav.orders': 'Фармоишҳои ман',
    'nav.profile': 'Профил',
    'nav.resale': 'Бозори моликиятдодашуда',
    'nav.settings': 'Танзимот',
    'nav.transactions': 'Амалиётҳо',
    'nav.withdraw': 'Пулкашӣ',
    'nav.recharge': 'Пардохт',
    'nav.referral': 'Даъватҳои ман',
    'nav.team': 'Омори гурӯҳ',
    'nav.menu': 'Меню',
    'nav.language': 'Забон',
    
    // Саҳифаи даъват
    'referral.title': 'Даъватҳои ман',
    'referral.subtitle': 'Дӯстонро даъват кунед, ҷойиз гиред',
    'referral.invite_code': 'Коди даъват',
    'referral.invite_link': 'Истиноди даъват',
    'referral.copy_code': 'Кодро нусхабардорӣ кунед',
    'referral.copy_link': 'Истинодро нусхабардорӣ кунед',
    'referral.share_code': 'Кодро мубодила кунед',
    'referral.share_link': 'Истинодро мубодила кунед',
    'referral.invite_friends': 'Дӯстонро даъват кунед',
    'referral.total_referrals': 'Даъватҳои умумӣ',
    'referral.level1_count': 'Сатҳи 1',
    'referral.level2_count': 'Сатҳи 2',
    'referral.level3_count': 'Сатҳи 3',
    'referral.total_rewards': 'Ҷойизҳои умумӣ',
    'referral.weekly_rewards': 'Ҷойизҳои ҳафта',
    'referral.stats_title': 'Омори даъват',
    'referral.copy_success': 'Бомуваффақият нусхабардорӣ шуд',
    'referral.copy_failed': 'Нусхабардорӣ карда натавонист',
    'referral.generating_link': 'Истинод сохта мешавад...',
    'referral.share_title': 'Ба LuckyMart TJ ҳамроҳ шавед',
    'referral.share_message': 'Рӯйхат гузоред ва ҷойизи корбари нав гиред! Коди ё инсони манро истифода баред:',
    'referral.telegram_share': 'Дар Telegram мубодила кунед',
    'referral.whatsapp_share': 'Дар WhatsApp мубодила кунед',
    'referral.social_share': 'Мубодилаи иҷтимоӣ',
    
    // Саҳифаи омори гурӯҳ
    'team.title': 'Омори гурӯҳ',
    'team.subtitle': 'Таҳлил ва идоракунии маълумоти гурӯҳ',
    'team.overview': 'Назари умумӣ',
    'team.growth': 'Рушд',
    'team.ranking': 'Рейтинг',
    'team.overview_title': 'Назари умумии гурӯҳ',
    'team.overview_subtitle': 'Омори асосии гурӯҳ',
    'team.growth_title': 'Рушди гурӯҳ',
    'team.growth_subtitle': 'Таҳлили хатти инкишофи гурӯҳ',
    'team.total_members': 'Аъзои умумӣ',
    'team.active_members': 'Аъзои фаъол',
    'team.active_rate': 'Нои фаъолӣ',
    'team.total_revenue': 'Даромади умумӣ',
    'team.level_distribution': 'Тақсимоти сатҳҳо',
    'team.level_distribution_desc': 'Тақсимоти аъзои гурӯҳ бо сатҳҳо',
    'team.level1': 'Сатҳи 1',
    'team.level2': 'Сатҳи 2',
    'team.level3': 'Сатҳи 3',
    'team.level4': 'Сатҳи 4',
    'team.level5': 'Сатҳи 5',
    'team.activity_stats': 'Омори фаъолӣ',
    'team.activity_stats_desc': 'Таҳлили фаъолияти аъзои гурӯҳ',
    'team.avg_active_days': 'Рӯзҳои фаъоли миёна',
    'team.most_active_days': 'Зиёдатин фаъолӣ',
    'team.least_active_days': 'Камтарин фаъолӣ',
    'team.overall_activity': 'Фаъолияти умумӣ',
    'team.new_members_trend': 'Хати инкишофи аъзои нав',
    'team.new_members_trend_desc': 'Рушди ҳозираи аъзои нав',
    'team.performance_overview': 'Назари қобилият',
    'team.performance_overview_desc': 'Нишондиҳандаҳои асосии қобилият',
    'team.top_performer': 'Беҳтарин натиҷа',
    'team.avg_revenue': 'Даромади миёна',
    'team.revenue_per_member': 'Даромад ба аъзо',
    'team.growth_rate': 'Суръати рушд',
    'team.member_growth_rate': 'Суръати рушди аъзо',
    'team.revenue_growth_rate': 'Суръати рушди даромад',
    'team.member_growth_trend': 'Хати инкишофи аъзо',
    'team.member_growth_trend_desc': 'Хати тағйироти шумораи аъзои гурӯҳ',
    'team.new_members': 'Аъзои нав',
    'team.revenue_growth_trend': 'Хати инкишофи даромад',
    'team.revenue_growth_trend_desc': 'Хати тағйироти даромади гурӯҳ',
    'team.revenue': 'Даромад',
    'team.comprehensive_growth_analysis': 'Таҳлили рушди ҳамаҷониба',
    'team.comprehensive_growth_analysis_desc': 'Таҳлили маълумоти рушди гурӯҳ дар чанд самт',
    'team.growth_insights': 'Дарки рушд',
    'team.member_growth_insight': 'Дарки рушди аъзо',
    'team.revenue_growth_insight': 'Дарки рушди даромад',
    'team.overall_performance': 'Қобилияти умумӣ',
    'team.positive_trend': 'Хати мусбат',
    'team.negative_trend': 'Хати манфӣ',
    'team.performance_ranking': 'Рейтинг қобилият',
    'team.referral_ranking': 'Рейтинг даъват',
    'team.referrals': 'Даъватҳо',
    'team.active_days': 'Рӯзҳои фаъол',
    'team.total_referrals': 'Даъватҳои умумӣ',
    'team.members': 'Аъзоҳо',
    
    // Маҳсулот
    'product.detail': 'Тафсилоти маҳсулот',
    'product.description': 'Вашфкунӣ',
    'product.market_price': 'Нархи бозор',
    'product.total_shares': 'Ҳиссаҳои умумӣ',
    'product.price_per_share': 'Нархи ҳисса',
    'product.participation_progress': 'Пешрафти иштирок',
    'product.remaining': 'Боқимонда',
    'product.select_shares': 'Ҳиссаҳоро интихоб кунед',
    'product.need_coins': 'Лозим',
    'product.participate_now': 'Ҳоло иштирок кунед',
    'product.participating': 'Иштирок мекунад...',
    'product.recent_participations': 'Иштироккунандагони охирин',
    'product.agree_rules': 'Бо иштирок шудан, шумо бо қоидаҳои платформа розӣ мешавед. Ба шумо муваффақият!',
    
    // Умумӣ
    'common.loading': 'Боркунӣ...',
    'common.shares': 'ҳисса',
    'common.coins': 'танга',
    'common.tjs': 'TJS',
    'common.back': 'Бозгашт',
    'common.confirm': 'Тасдиқ',
    'common.cancel': 'Бекоркунӣ',
    
    // Маъмур
    'admin.welcome': 'Хуш омадед',
    'admin.logout': 'Баромадан',
    
    // Идоракунии ҷойизҳо
    'admin.reward_config.title': 'Идоракунии ҷойизҳо',
    'admin.reward_config.subtitle': 'Идоракунии параметрҳои ҷойиз ва сатҳҳои даъват',
    'admin.reward_config.search_placeholder': 'Ҷустуҷӯи калиди ё ном...',
    'admin.reward_config.add_new': 'Илова кардан',
    'admin.reward_config.total_configs': 'Конфигуратсияҳои умумӣ',
    'admin.reward_config.active_configs': 'Конфигуратсияҳои фаъол',
    'admin.reward_config.inactive_configs': 'Конфигуратсияҳои ғайрифаъол',
    'admin.reward_config.current_page': 'Саҳифаи ҳозира',
    'admin.reward_config.no_configs': 'Конфигуратсия нест',
    'admin.reward_config.no_configs_description': 'Барои сохтани аввалин конфигуратсияҳои ҷойиз тугмаи иловаро пахш кунед',
    'admin.reward_config.config_key': 'Калиди конфигуратсия',
    'admin.reward_config.config_name': 'Номи конфигуратсия',
    'admin.reward_config.reward_amount': 'Маблағи ҷойиз',
    'admin.reward_config.referral_level': 'Сатҳи даъват',
    'admin.reward_config.status': 'Ҳолат',
    'admin.reward_config.updated_at': 'Навсозӣ шудааст',
    'admin.reward_config.updated_by': 'Навсозӣ карда',
    'admin.reward_config.actions': 'Амалҳо',
    'admin.reward_config.active': 'Фаъол',
    'admin.reward_config.inactive': 'Ғайрифаъол',
    'admin.reward_config.level': 'Сатҳ',
    'admin.reward_config.no_level': 'Бе сатҳ',
    'admin.reward_config.all_levels': 'Ҳама сатҳҳо',
    'admin.reward_config.all_status': 'Ҳама ҳолатҳо',
    'admin.reward_config.edit': 'Таҳрир',
    'admin.reward_config.deactivate': 'Ғайрифаъолкунӣ',
    'admin.reward_config.activate': 'Фаъолкунӣ',
    'admin.reward_config.previous': 'Қаблӣ',
    'admin.reward_config.next': 'Баъдӣ',
    'admin.reward_config.page_info': 'Саҳифаи {page} аз {totalPages}',
    'admin.reward_config.add_config': 'Конфигуратсия илова кунед',
    'admin.reward_config.edit_config': 'Конфигуратсияро таҳрир кунед',
    'admin.reward_config.select_template': 'Намуна интихоб кунед',
    'admin.reward_config.config_key_placeholder': 'масалан register_referrer',
    'admin.reward_config.config_name_placeholder': 'масалан Ҷойизи даъваткунандаи нав',
    'admin.reward_config.config_description_placeholder': 'Вашфкунии конфигуратсия (ихтиёрӣ)...',
    'admin.reward_config.referral_level_description': 'Сатҳи даъват барои ин ҷойиз муқаррар кунед',
    'admin.reward_config.enable_config': 'Ин конфигуратсияро фаъол кунед',
    'admin.reward_config.update': 'Навсозӣ',
    'admin.reward_config.create': 'Сохтан',
    'admin.reward_config.updating': 'Навсозӣ мешавад...',
    'admin.reward_config.creating': 'Сохта мешавад...',
    
    // Идоракунии таърихи тағйироти конфигуратсия
    'admin.config_history.title': 'Идоракунии таърихи конфигуратсия',
    'admin.config_history.subtitle': 'Дидани таърихи тағйироти конфигуратсия ва ҳисобҳои аудит',
    'admin.config_history.search': 'Ҷустуҷӯ',
    'admin.config_history.reset': 'Аз нав танзимкунӣ',
    'admin.config_history.startDate': 'Санаи оғоз',
    'admin.config_history.endDate': 'Санаи анҷом',
    'admin.config_history.updatedBy': 'Тағйиркунанда',
    'admin.config_history.configKey': 'Калиди конфигуратсия',
    'admin.config_history.time': 'Вақт',
    'admin.config_history.modifier': 'Тағйиркунанда',
    'admin.config_history.beforeValue': 'Қимати қаблӣ',
    'admin.config_history.afterValue': 'Қимати нав',
    'admin.config_history.ipAddress': 'Нишонаи IP',
    'admin.config_history.changeType': 'Навъи тағйирот',
    'admin.config_history.create': 'Сохтан',
    'admin.config_history.delete': 'Несткунӣ',
    'admin.config_history.increase': 'Афзоиш',
    'admin.config_history.decrease': 'Камкунӣ',
    'admin.config_history.modify': 'Таҳриркунӣ',
    'admin.config_history.none': 'Нест',
    'admin.config_history.page': 'Саҳифа',
    'admin.config_history.of': 'аз',
    'admin.config_history.total': 'Умумӣ',
    'admin.config_history.noRecords': 'Ягон сабт ёфт нашуд',
    'admin.config_history.loading': 'Боркунӣ...',
    'admin.config_history.placeholder.key': 'Калиди конфигуратсияро ворид кунед...',
    'admin.config_history.placeholder.modifier': 'Тағйиркунандаро ворид кунед...',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('zh');
  const [isLoading, setIsLoading] = useState(false);

  // 从localStorage读取语言设置
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['zh', 'en', 'ru', 'tg'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  // 改进的语言切换函数
  const setLanguage = useCallback(async (lang: Language) => {
    if (lang === language) return;
    
    setIsLoading(true);
    
    try {
      setLanguageState(lang);
      localStorage.setItem('language', lang);
      
      // 触发自定义事件通知其他组件
      window.dispatchEvent(new CustomEvent('languageChange', { 
        detail: { language: lang } 
      }));
      
      // 可选：发送到服务器同步用户偏好
      await syncLanguagePreference(lang);
      
    } catch (error) {
      console.error('语言切换失败:', error);
    } finally {
      setIsLoading(false);
    }
  }, [language]);

  // 翻译函数
  const t = useCallback((key: string): string => {
    return translations[language]?.[key] || key;
  }, [language]);

  // 同步语言偏好到服务器
  const syncLanguagePreference = async (lang: Language) => {
    try {
      await fetch('/api/user/language', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ language: lang }),
      });
    } catch (error) {
      // 静默失败，不影响用户体验
      console.warn('同步语言偏好失败:', error);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isLoading }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
